---
- name: Deploy simple web page & Setup firewall
  hosts: all

  vars:
    source_file: ./web-page/index.html
    dest_file: /var/www/html

  tasks:
  - name: Install Apache web server
    yum:
      name: httpd
      # we can also use specific version of Apache
      # name: httpd = 2.4.37
      state: present

  - name: Copy web page
    copy:
      src: "{{ source_file }}"
      dest: "{{ dest_file }}"
      mode: 0644
    notify:
    - Restart Apache

  - name: Start Apache and enable it on the every boot
    service:
      name: httpd
      state: started
      enabled: yes
  
  - name: Start FirewallD service
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Add port to firewalld
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
    notify:
    - Restart firewalld service

  handlers:
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
  
  - name: Restart firewalld service 
    service:
      name: firewalld
      state: restarted
...