---
# handlers file for apache

  - name: Restart Apache
    service:
      name: httpd
      state: restarted
  
  - name: Restart firewalld service 
    service:
      name: firewalld
      state: restarted