---
# handlers file for vsftpd

- name: Restart vsftpd service
  service:
    name: vsftpd
    state: restarted

- name: Restart firewalld service 
  service:
    name: firewalld
    state: restarted

- name: Run restorecon
  command: restorecon -vR /var/ftp/pub